import Head from 'next/head'
import Link from 'next/link'

const Navbar = ({ navigation }) => {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <ul>
                {navigation && navigation.map((page) => {
                    let item;

                    if (page.path == '/') {
                        item = (
                            <li key={page.id}>
                                <Link href="/">
                                    <a>{page.title}</a>
                                </Link>
                            </li>
                        )
                        return item;

                    } else {

                        if (page.type === 'EXTERNAL' && page.parent === null) {
                            item = (
                                <li key={page.id}>
                                    <a href={page.externalPath}>
                                        {page.title}
                                    </a>
                                </li>
                            )
                            return item;
                        }

                        if (page.type === 'INTERNAL' && page.parent === null) {
                            item = (
                                <li key={page.id}>
                                    <Link
                                        href={{
                                            pathname: '/[slug]',
                                            query: {
                                                slug: page.related.slug
                                            },
                                        }}
                                    >
                                        <a>{page.title}</a>
                                    </Link>
                                </li>
                            )
                            return item;
                        }

                        if (page.type === 'WRAPPER') {
                            item = (
                                <li key={page.id}>
                                    <span>{page.title}</span>
                                    <ul>
                                        {navigation && navigation.map((subpage) => {
                                            if (subpage.parent !== null) {
                                                if (subpage.parent.id === page.id) {
                                                    if (subpage.type === 'EXTERNAL') {
                                                        item = (
                                                            <li key={subpage.id}>
                                                                <a href={subpage.externalPath}>
                                                                    {subpage.title}
                                                                </a>
                                                            </li>
                                                        )
                                                        return item;
                                                    }
    
                                                    if (subpage.type === 'INTERNAL') {
                                                        item = (
                                                            <li key={subpage.id}>
                                                                <Link
                                                                    href={{
                                                                        pathname: '/[slug]',
                                                                        query: {
                                                                            slug: subpage.related.slug
                                                                        },
                                                                    }}
                                                                    as={`/${subpage.parent.path}/${subpage.related.slug}`}
                                                                >
                                                                    <a>{subpage.title}</a>
                                                                </Link>
                                                            </li>
                                                        )
                                                        return item
                                                    }
                                                }
                                            }
                                        })}
                                    </ul>
                                </li>
                            )
                            return item;
                        }
                    }
                })}
            </ul>
        </>
    )
}

export default Navbar;